export const ADD_TO_CART ="ADD_TO_CART"
export const REMOVE_ITEM ="REMOVE_ITEM"
export const REMOVE_ALL ="REMOVE_ALL"
export const SET_ALL ="SET_ALL"
export const SET_USER ="SET_USER"
export const LOG_OUT ="LOG_OUT"