export const WHITE = '#FFFFFF';
export const BLACK = '#000000';
export const GRAY = '#949494';
export const MID_GRAY = '#AEAEAE';
export const SEC_GRAY = '#ccc';
export const LIGHT_GRAY = '#EEECF1';
export const GREEN = '#34C759';
export const OVERLAY = 'rgba(0,0,0,0.7)';
export const BG_SHADE = 'rgba(0,0,0,0.2)';
export const LIGHT_BLUE ="#ADC3D1"
export const NAVY_BLUE ="#2C406E"
export const BLUE ="#759CC9"
export const SKY_BLUE ="#42A7E5"
export const SECONDARY_BLUE ="#62A7E5"
export const FERRARI_RED ="#FF6B53"
export const SWISS_RED ="#DA291C"
export const LIME_GREEN ="#84CA93"
export const GOLD_YELLOW ="#FFA902"
